### ISSUE TITLE
Hi! I'm having bit trouble with stickyRows - does it requires a thead?

### ISSUE THREAD

**Issue by ecerichter** [maslianok/stickyRows#1]
Thanks for publishing this code.
I'm trying to use it togheter with GWT (which doesn't generate thead object in html table).
Can I just fix the first row in the tbody element?
Whenever I try to do that, I get a "cannot read property split of undefined" - which leads to the following code:

```
        // current settings
        this.opts = $.extend(
            {},
            $.StickyRows.opts,
            this.table.$element.data(),
            options
        );
```

I'll appreciate your help.

Regards,

Edson

**Comment by maslianok** [comment]
No, it doesn't require `<thead>` element, but I strongly recommend you to use `<thead>` or `<tbody>`.

Example without thead:

```
<table>
  <tbody class="first">
    <tr><td>1</td></tr>
    <tr><td>2</td></tr>
  </tbody>
  <tbody class="second">
    <tr><td>3</td></tr>
    <tr><td>4</td></tr>
  </tbody>
</table>
```

``` javascript
$('table').stickyRows({
  rows: '.first'
});
```

You also can use it without any `<thead>` or `<tbody>` containers. But please, make sure that browser doesn't add them for you.
For example, this html

```
<table>
    <tr><td>1</td></tr>
    <tr><td>2</td></tr>
    <tr><td>3</td></tr>
    <tr><td>4</td></tr>
</table>
```

Google Chrome will render as  

```
<table>
  <tbody>
    <tr><td>1</td></tr>
    <tr><td>2</td></tr>
    <tr><td>3</td></tr>
    <tr><td>4</td></tr>
  </tbody>
</table>
```

**Comment by ecerichter** [comment]
Thankyou very much.Unfortunately, I wasn't able to integrate StickyRows with GWT.I must be doing something terrible mistaken, because I always get the error "cannot access key attribute on nothing" (or similar, depends on the browser I'm running on).
Thanks for your help anyway.
Regards,
Edson Richter

Date: Wed, 9 Jul 2014 00:52:55 -0700
