### ISSUE TITLE
Doctype stopping this from working

### ISSUE THREAD

**Issue by jeremymjones** [maslianok/stickyRows#2]
Hello

Just to report a bug in this.

It seems that as soon as you use a doctype, the stickyRows no longer stick - remove the doctype and everything works as expected.

Kind regards,

Jeremy

**Comment by maslianok** [comment]
Yep. Adding a DOCTYPE switches you from quirks mode to standards mode. In standards mode, the html and body elements do not default to 100% of the size of the viewport.
So with DOCTYPE you need to set html and body height to 100%:

```
html, body {
    height: 100%;
}
```

I was fixed this in my last commit.

**Comment by jeremymjones** [comment]
Great stuff - thanks very much.
