### ISSUE TITLE
HTML5 support

### ISSUE THREAD

**Issue by spekulatius** [maslianok/stickyRows#3]
Hello Maslianok,

I found a issue using stickyrows at a HTML5 page. I have a table with multiple heads in between which 'get scrolled' out one by one. It works fine, but only when I remove the HTML5 doctype definition from the document. With HTML5 def it doesn't work. Is this a known problem? Is there a easy way to solve this?

Cheers,
spek

**Comment by maslianok** [comment]
Hi, spekulatius,
Please look at issue https://github.com/maslianok/stickyRows/issues/2
Hope it helps...
