### ISSUE TITLE
Not working with Firefox

### ISSUE THREAD

**Issue by uikid** [maslianok/stickyRows#4]
OS: Windows 7 / 8, OS X 10
Firefox Version: 37.0.2

stickyRows is not working with Firefox.

**Comment by BenDol** [comment]
Same with IE11

**Comment by ByronDDelpinal** [comment]
Any plans on getting this working cross browser with IE11 and Firefox? Would love to use the library, great job so far!

**Comment by maslianok** [comment]
Sorry, guys. Unfortunately, I don't plan to support this library anymore.

If you know how to fix it - you can still create a PR.
