### ISSUE TITLE
border-collapse issue

### ISSUE THREAD

**Issue by ghost** [maslianok/stickyRows#5]
Your plugin is super easy to use and exactly what I'm looking for. However, when I use it on thead with the table having "border-collapse: collapse", it is misaligned with the rest of the table. Also, there are 2-3px borders appearing around the cells in the sticky element that are not being added by me and no amount of overriding seems to be affecting them. It also increases the size of my font. Any ideas on how to address this?

**Comment by maslianok** [comment]
Sorry @mluyties but I don't support this plugin anymore.
You can make a fork and change it to your needs.
